name: Sync Repository 1:1 to Pelican (Strict SFTP)

on:
  push:
    branches:
      - '*' # Reagiert auf jeden Branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true # Verhindert, dass GitHub den Job als Fehlschlag wertet und E-Mails sendet
    steps:
      - name: 1. Code aus Git auschecken
        uses: actions/checkout@v4

      - name: 2. 1:1 Spiegelung via LFTP (Strict SFTP)
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -e "
            set sftp:connect-program 'ssh -a -x -p 2022 -o StrictHostKeyChecking=no';
            set sftp:auto-confirm yes;
            open -u '\${{ secrets.PELICAN_SFTP_USER }}','\({{ secrets.PELICAN_SFTP_PASSWORD }}' sftp://\){{ secrets.PELICAN_SFTP_HOST }};
            mirror --reverse --delete --verbose ./ ./;
            quit;
          "